### ISSUE TITLE
縮排有規定嗎

### ISSUE THREAD

**Issue by wei-coding** [liao2000/Cocaine#1]
```asm=
import:
    io

main:                           ; main segment
	io.echo "Hello coco"        ; call function
```
main後面的縮排似乎和import的縮排不一樣，有規定嗎？

**Comment by ksw2000** [comment]
Hello, wei-coding
Cocaine support `2 spaces`, `4 spaces` or `1 tab` indent

> ```
> import:
>     io
> 
> main:                           ; main segment
> 	io.echo "Hello coco"        ; call function
> ```
> 
> main後面的縮排似乎和import的縮排不一樣，有規定嗎？

**Comment by twjmy** [comment]
What if `1 space` or `3 spaces` ?

> Hello, wei-coding
> Cocaine support `2 spaces`, `4 spaces` or `1 tab` indent
> 
> > ```
> > import:
> >     io
> > 
> > main:                           ; main segment
> > 	io.echo "Hello coco"        ; call function
> > ```
> > 
> > 
> > main後面的縮排似乎和import的縮排不一樣，有規定嗎？
