### ISSUE TITLE
Code Compression?

### ISSUE THREAD

**Issue by twjmy** [liao2000/Cocaine#2]
As title, whatif I need a compression of a cocaine code?
Python allow us to use `python -c <command>` by passing compressed one line string code like `"print('hello');print('world')"` in terminal, and it also works in simple code.
C is always allow us to compress our code.
How about the way to compress the code in cocaine?
And, does its compiler support such command in terminal?

**Comment by ksw2000** [comment]
Cocaine does not support compression code currently
