### ISSUE TITLE
再混 R 蛤

### ISSUE THREAD

**Issue by tomy0000000** [liao2000/Cocaine#3]
@wei-coding
@Minniemu

撻伐他啦

**Comment by wei-coding** [comment]
原來是全新的聊天室 我還以為是issue欸

**Comment by Tora0615** [comment]
@tomy0000000  下次撻伐+1辣

**Comment by ksw2000** [comment]
Assembly 沒學好寫不出來，要大佬們的幫忙

**Comment by wei-coding** [comment]
@tomy0000000 @Minniemu @Tora0615

再次撻伐

**Comment by tomy0000000** [comment]
![](https://memeprod.sgp1.digitaloceanspaces.com/user-wtf/1584000069314.jpg)

**Comment by Tora0615** [comment]
@wei-coding 
![received_407751880671882.jpeg](https://user-images.githubusercontent.com/33981880/127520235-958ea44e-b16c-4829-9667-6409a18fd683.jpeg)

**Comment by wei-coding** [comment]
![maxresdefault](https://user-images.githubusercontent.com/42136402/127524090-f94aa8b4-847f-48b3-b497-58017723d89a.jpg)

**Comment by wei-coding** [comment]
> @wei-coding
> ![received_407751880671882.jpeg](https://user-images.githubusercontent.com/33981880/127520235-958ea44e-b16c-4829-9667-6409a18fd683.jpeg)

你484想在這裡開車

**Comment by ksw2000** [comment]
各位同胞們，小弟已經用 go 刻了一個大概的樣子出來了
